name: Automated Release Workflow

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Configure Git User Info
        run: |
          git config --local user.name "Asger Jon Vistisen"
          git config --local user.email "asgerjon2@gmail.com"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version build

      - name: Bump Version and Tag
        run: |
          bump2version patch --commit --tag

      - name: Push Changes
        run: |
          git push && git push --tags

      - name: Build Package
        run: python -m build

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
